/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetReportRelayRefreshResponse : AssetReportRelayRefreshResponse defines the response schema for `/asset_report/relay/refresh`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetReportRelayRefreshResponse {
    #[serde(rename = "asset_relay_token")]
    pub asset_relay_token: String,
    /// A unique ID identifying an Asset Report. Like all Plaid identifiers, this ID is case sensitive.
    #[serde(rename = "asset_report_id")]
    pub asset_report_id: String,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl AssetReportRelayRefreshResponse {
    /// AssetReportRelayRefreshResponse defines the response schema for `/asset_report/relay/refresh`
    pub fn new(asset_relay_token: String, asset_report_id: String, request_id: String) -> AssetReportRelayRefreshResponse {
        AssetReportRelayRefreshResponse {
            asset_relay_token,
            asset_report_id,
            request_id,
        }
    }
}


