/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetReportRelayRefreshRequest : AssetReportRelayRefreshRequest defines the request schema for `/asset_report/relay/refresh`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetReportRelayRefreshRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    #[serde(rename = "asset_relay_token")]
    pub asset_relay_token: String,
    /// The URL registered to receive webhooks when the Asset Report of a Relay Token has been refreshed.
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<String>,
}

impl AssetReportRelayRefreshRequest {
    /// AssetReportRelayRefreshRequest defines the request schema for `/asset_report/relay/refresh`
    pub fn new(asset_relay_token: String) -> AssetReportRelayRefreshRequest {
        AssetReportRelayRefreshRequest {
            client_id: None,
            secret: None,
            asset_relay_token,
            webhook: None,
        }
    }
}


