/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// CountryCode : ISO-3166-1 alpha-2 country code standard.

/// ISO-3166-1 alpha-2 country code standard.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CountryCode {
    #[serde(rename = "US")]
    US,
    #[serde(rename = "GB")]
    GB,
    #[serde(rename = "ES")]
    ES,
    #[serde(rename = "NL")]
    NL,
    #[serde(rename = "FR")]
    FR,
    #[serde(rename = "IE")]
    IE,
    #[serde(rename = "CA")]
    CA,
    #[serde(rename = "DE")]
    DE,
    #[serde(rename = "IT")]
    IT,
}

impl ToString for CountryCode {
    fn to_string(&self) -> String {
        match self {
            Self::US => String::from("US"),
            Self::GB => String::from("GB"),
            Self::ES => String::from("ES"),
            Self::NL => String::from("NL"),
            Self::FR => String::from("FR"),
            Self::IE => String::from("IE"),
            Self::CA => String::from("CA"),
            Self::DE => String::from("DE"),
            Self::IT => String::from("IT"),
        }
    }
}

impl Default for CountryCode {
    fn default() -> CountryCode {
        Self::US
    }
}
