/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreditBankIncomePayFrequency : The income pay frequency.

/// The income pay frequency.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreditBankIncomePayFrequency {
    #[serde(rename = "WEEKLY")]
    WEEKLY,
    #[serde(rename = "BIWEEKLY")]
    BIWEEKLY,
    #[serde(rename = "SEMI_MONTHLY")]
    SEMIMONTHLY,
    #[serde(rename = "MONTHLY")]
    MONTHLY,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,

}

impl ToString for CreditBankIncomePayFrequency {
    fn to_string(&self) -> String {
        match self {
            Self::WEEKLY => String::from("WEEKLY"),
            Self::BIWEEKLY => String::from("BIWEEKLY"),
            Self::SEMIMONTHLY => String::from("SEMI_MONTHLY"),
            Self::MONTHLY => String::from("MONTHLY"),
            Self::UNKNOWN => String::from("UNKNOWN"),
        }
    }
}

impl Default for CreditBankIncomePayFrequency {
    fn default() -> CreditBankIncomePayFrequency {
        Self::WEEKLY
    }
}




