/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreditBankIncomeCategory : The income category.

/// The income category.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreditBankIncomeCategory {
    #[serde(rename = "SALARY")]
    SALARY,
    #[serde(rename = "UNEMPLOYMENT")]
    UNEMPLOYMENT,
    #[serde(rename = "CASH")]
    CASH,
    #[serde(rename = "GIG_ECONOMY")]
    GIGECONOMY,
    #[serde(rename = "RENTAL")]
    RENTAL,
    #[serde(rename = "CHILD_SUPPORT")]
    CHILDSUPPORT,
    #[serde(rename = "MILITARY")]
    MILITARY,
    #[serde(rename = "RETIREMENT")]
    RETIREMENT,
    #[serde(rename = "LONG_TERM_DISABILITY")]
    LONGTERMDISABILITY,
    #[serde(rename = "BANK_INTEREST")]
    BANKINTEREST,
    #[serde(rename = "OTHER")]
    OTHER,
}

impl ToString for CreditBankIncomeCategory {
    fn to_string(&self) -> String {
        match self {
            Self::SALARY => String::from("SALARY"),
            Self::UNEMPLOYMENT => String::from("UNEMPLOYMENT"),
            Self::CASH => String::from("CASH"),
            Self::GIGECONOMY => String::from("GIG_ECONOMY"),
            Self::RENTAL => String::from("RENTAL"),
            Self::CHILDSUPPORT => String::from("CHILD_SUPPORT"),
            Self::MILITARY => String::from("MILITARY"),
            Self::RETIREMENT => String::from("RETIREMENT"),
            Self::LONGTERMDISABILITY => String::from("LONG_TERM_DISABILITY"),
            Self::BANKINTEREST => String::from("BANK_INTEREST"),
            Self::OTHER => String::from("OTHER"),
        }
    }
}

impl Default for CreditBankIncomeCategory {
    fn default() -> CreditBankIncomeCategory {
        Self::SALARY
    }
}
