/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// Enhancements : A grouping of the Plaid produced transaction enhancement fields.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Enhancements {
    /// The merchant name, as extracted by Plaid from the raw description.
    #[serde(rename = "merchant_name", skip_serializing_if = "Option::is_none")]
    pub merchant_name: Option<String>,
    /// The check number of the transaction. This field is only populated for check transactions.
    #[serde(rename = "check_number", skip_serializing_if = "Option::is_none")]
    pub check_number: Option<String>,
    #[serde(rename = "payment_channel")]
    pub payment_channel: crate::models::PaymentChannel,
    /// The ID of the category to which this transaction belongs. For a full list of categories, see [`/categories/get`](https://plaid.com/docs/api/products/#categoriesget).
    #[serde(rename = "category_id")]
    pub category_id: Option<String>,
    /// A hierarchical array of the categories to which this transaction belongs. For a full list of categories, see [`/categories/get`](https://plaid.com/docs/api/products/#categoriesget).
    #[serde(rename = "category")]
    pub category: Vec<String>,
    #[serde(rename = "location")]
    pub location: crate::models::Location,
    #[serde(
        rename = "personal_finance_category",
        skip_serializing_if = "Option::is_none"
    )]
    pub personal_finance_category: Option<crate::models::PersonalFinanceCategory>,
}

impl Enhancements {
    /// A grouping of the Plaid produced transaction enhancement fields.
    pub fn new(
        payment_channel: crate::models::PaymentChannel,
        category_id: Option<String>,
        category: Vec<String>,
        location: crate::models::Location,
    ) -> Enhancements {
        Enhancements {
            merchant_name: None,
            check_number: None,
            payment_channel,
            category_id,
            category,
            location,
            personal_finance_category: None,
        }
    }
}
