/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// ExternalPaymentInitiationConsentOptions : Additional payment consent options

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExternalPaymentInitiationConsentOptions {
    /// The EMI (E-Money Institution) wallet that this payment consent is associated with, if any. This wallet is used as an intermediary account to enable Plaid to reconcile the settlement of funds for Payment Initiation requests.
    #[serde(rename = "wallet_id", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    /// When `true`, Plaid will attempt to request refund details from the payee's financial institution.  Support varies between financial institutions and will not always be available.  If refund details could be retrieved, they will be available in the `/payment_initiation/payment/get` response.
    #[serde(
        rename = "request_refund_details",
        skip_serializing_if = "Option::is_none"
    )]
    pub request_refund_details: Option<bool>,
}

impl ExternalPaymentInitiationConsentOptions {
    /// Additional payment consent options
    pub fn new() -> ExternalPaymentInitiationConsentOptions {
        ExternalPaymentInitiationConsentOptions {
            wallet_id: None,
            request_refund_details: None,
        }
    }
}
