/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IdentityUpdateTypes : The possible types of identity data that may have changed.

/// The possible types of identity data that may have changed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IdentityUpdateTypes {
    #[serde(rename = "PHONES")]
    PHONES,
    #[serde(rename = "ADDRESSES")]
    ADDRESSES,
    #[serde(rename = "EMAILS")]
    EMAILS,
    #[serde(rename = "NAMES")]
    NAMES,

}

impl ToString for IdentityUpdateTypes {
    fn to_string(&self) -> String {
        match self {
            Self::PHONES => String::from("PHONES"),
            Self::ADDRESSES => String::from("ADDRESSES"),
            Self::EMAILS => String::from("EMAILS"),
            Self::NAMES => String::from("NAMES"),
        }
    }
}

impl Default for IdentityUpdateTypes {
    fn default() -> IdentityUpdateTypes {
        Self::PHONES
    }
}




