/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// LinkTokenCreateRequestIncomeVerificationPayrollIncome : Specifies options for initializing Link for use with Payroll Income. This field is required if `income_verification` is included in the `products` array and `payroll` is specified in `income_source_types`.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestIncomeVerificationPayrollIncome {
    /// The types of payroll income verification to enable for the link session. If none are specified, then users will see both document and digital payroll income.
    #[serde(rename = "flow_types", skip_serializing_if = "Option::is_none")]
    pub flow_types: Option<Vec<crate::models::IncomeVerificationPayrollFlowType>>,
}

impl LinkTokenCreateRequestIncomeVerificationPayrollIncome {
    /// Specifies options for initializing Link for use with Payroll Income. This field is required if `income_verification` is included in the `products` array and `payroll` is specified in `income_source_types`.
    pub fn new() -> LinkTokenCreateRequestIncomeVerificationPayrollIncome {
        LinkTokenCreateRequestIncomeVerificationPayrollIncome { flow_types: None }
    }
}
