/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// PaymentInitiationConsentConstraints : Limitations that will be applied to payments initiated using the payment consent.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentInitiationConsentConstraints {
    #[serde(rename = "valid_date_time", skip_serializing_if = "Option::is_none")]
    pub valid_date_time: Option<crate::models::PaymentConsentValidDateTime>,
    #[serde(rename = "max_payment_amount", skip_serializing_if = "Option::is_none")]
    pub max_payment_amount: Option<Box<crate::models::PaymentConsentMaxPaymentAmount>>,
    /// A list of amount limitations per period of time.
    #[serde(rename = "periodic_amounts", skip_serializing_if = "Option::is_none")]
    pub periodic_amounts: Option<Vec<crate::models::PaymentConsentPeriodicAmount>>,
}

impl PaymentInitiationConsentConstraints {
    /// Limitations that will be applied to payments initiated using the payment consent.
    pub fn new() -> PaymentInitiationConsentConstraints {
        PaymentInitiationConsentConstraints {
            valid_date_time: None,
            max_payment_amount: None,
            periodic_amounts: None,
        }
    }
}
