/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// PaymentAmountCurrency : The ISO-4217 currency code of the payment. For standing orders and payment consents, `\"GBP\"` must be used.

/// The ISO-4217 currency code of the payment. For standing orders and payment consents, `\"GBP\"` must be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentAmountCurrency {
    #[serde(rename = "GBP")]
    GBP,
    #[serde(rename = "EUR")]
    EUR,
}

impl ToString for PaymentAmountCurrency {
    fn to_string(&self) -> String {
        match self {
            Self::GBP => String::from("GBP"),
            Self::EUR => String::from("EUR"),
        }
    }
}

impl Default for PaymentAmountCurrency {
    fn default() -> PaymentAmountCurrency {
        Self::GBP
    }
}
