/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// PaymentConsentPeriodicInterval : Payment consent periodic interval.

/// Payment consent periodic interval.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentConsentPeriodicInterval {
    #[serde(rename = "DAY")]
    DAY,
    #[serde(rename = "WEEK")]
    WEEK,
    #[serde(rename = "MONTH")]
    MONTH,
    #[serde(rename = "YEAR")]
    YEAR,
}

impl ToString for PaymentConsentPeriodicInterval {
    fn to_string(&self) -> String {
        match self {
            Self::DAY => String::from("DAY"),
            Self::WEEK => String::from("WEEK"),
            Self::MONTH => String::from("MONTH"),
            Self::YEAR => String::from("YEAR"),
        }
    }
}

impl Default for PaymentConsentPeriodicInterval {
    fn default() -> PaymentConsentPeriodicInterval {
        Self::DAY
    }
}
