/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// PaymentInitiationRefund : PaymentInitiationRefund defines a payment initiation refund

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentInitiationRefund {
    /// The ID of the refund. Like all Plaid identifiers, the `refund_id` is case sensitive.
    #[serde(rename = "refund_id")]
    pub refund_id: String,
    #[serde(rename = "amount")]
    pub amount: crate::models::PaymentAmount,
    #[serde(rename = "status")]
    pub status: crate::models::PaymentInitiationRefundStatus,
    /// The date and time of the last time the `status` was updated, in IS0 8601 format
    #[serde(rename = "last_status_update")]
    pub last_status_update: String,
}

impl PaymentInitiationRefund {
    /// PaymentInitiationRefund defines a payment initiation refund
    pub fn new(
        refund_id: String,
        amount: crate::models::PaymentAmount,
        status: crate::models::PaymentInitiationRefundStatus,
        last_status_update: String,
    ) -> PaymentInitiationRefund {
        PaymentInitiationRefund {
            refund_id,
            amount,
            status,
            last_status_update,
        }
    }
}
