/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentConsentValidDateTime : Life span for the payment consent. After the `to` date the payment consent expires and can no longer be used for payment initiation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentConsentValidDateTime {
    /// The date and time from which the consent should be active, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// The date and time at which the consent expires, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
}

impl PaymentConsentValidDateTime {
    /// Life span for the payment consent. After the `to` date the payment consent expires and can no longer be used for payment initiation.
    pub fn new() -> PaymentConsentValidDateTime {
        PaymentConsentValidDateTime {
            from: None,
            to: None,
        }
    }
}


