/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// RelayEvent : The webhook code indicating which endpoint was called. It can be one of `GET_CALLED`, `REFRESH_CALLED` or `AUDIT_COPY_CREATE_CALLED`.

/// The webhook code indicating which endpoint was called. It can be one of `GET_CALLED`, `REFRESH_CALLED` or `AUDIT_COPY_CREATE_CALLED`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RelayEvent {
    #[serde(rename = "GET_CALLED")]
    GETCALLED,
    #[serde(rename = "REFRESH_CALLED")]
    REFRESHCALLED,
    #[serde(rename = "AUDIT_COPY_CREATE_CALLED")]
    AUDITCOPYCREATECALLED,
}

impl ToString for RelayEvent {
    fn to_string(&self) -> String {
        match self {
            Self::GETCALLED => String::from("GET_CALLED"),
            Self::REFRESHCALLED => String::from("REFRESH_CALLED"),
            Self::AUDITCOPYCREATECALLED => String::from("AUDIT_COPY_CREATE_CALLED"),
        }
    }
}

impl Default for RelayEvent {
    fn default() -> RelayEvent {
        Self::GETCALLED
    }
}
