/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransactionsRuleType : Transaction rule's match type. For TRANSACTION_ID field, EXACT_MATCH is available. Matches are case sensitive.

/// Transaction rule's match type. For TRANSACTION_ID field, EXACT_MATCH is available. Matches are case sensitive.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionsRuleType {
    #[serde(rename = "EXACT_MATCH")]
    EXACTMATCH,
    #[serde(rename = "SUBSTRING_MATCH")]
    SUBSTRINGMATCH,
}

impl ToString for TransactionsRuleType {
    fn to_string(&self) -> String {
        match self {
            Self::EXACTMATCH => String::from("EXACT_MATCH"),
            Self::SUBSTRINGMATCH => String::from("SUBSTRING_MATCH"),
        }
    }
}

impl Default for TransactionsRuleType {
    fn default() -> TransactionsRuleType {
        Self::EXACTMATCH
    }
}
