/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransactionsRulesListRequest : TransactionsRulesListRequest defines the request schema for `/transactions/rules/list`

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionsRulesListRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// The access token associated with the Item data is being requested for.
    #[serde(rename = "access_token")]
    pub access_token: String,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl TransactionsRulesListRequest {
    /// TransactionsRulesListRequest defines the request schema for `/transactions/rules/list`
    pub fn new(
        client_id: String,
        access_token: String,
        secret: String,
    ) -> TransactionsRulesListRequest {
        TransactionsRulesListRequest {
            client_id,
            access_token,
            secret,
        }
    }
}
