/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.84.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionStreamStatus : The current status of the transaction stream.  `mature`: A mature recurring stream should have at least 3 transactions and happen on a regular cadence.   `early_detection`: When a recurring transaction first appears in the transaction history and before it fulfills the requirement of a mature stream, we set the status as early_detection.  `tombstoned`: An early_detection stream would be tombstoned if no further transactions were found at the next expected date.  `unknown`: A stream is assigned an unknown status when none of the other statuses are applicable.

/// The current status of the transaction stream.  `mature`: A mature recurring stream should have at least 3 transactions and happen on a regular cadence.   `early_detection`: When a recurring transaction first appears in the transaction history and before it fulfills the requirement of a mature stream, we set the status as early_detection.  `tombstoned`: An early_detection stream would be tombstoned if no further transactions were found at the next expected date.  `unknown`: A stream is assigned an unknown status when none of the other statuses are applicable.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionStreamStatus {
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,
    #[serde(rename = "MATURE")]
    MATURE,
    #[serde(rename = "EARLY_DETECTION")]
    EARLYDETECTION,
    #[serde(rename = "TOMBSTONED")]
    TOMBSTONED,

}

impl ToString for TransactionStreamStatus {
    fn to_string(&self) -> String {
        match self {
            Self::UNKNOWN => String::from("UNKNOWN"),
            Self::MATURE => String::from("MATURE"),
            Self::EARLYDETECTION => String::from("EARLY_DETECTION"),
            Self::TOMBSTONED => String::from("TOMBSTONED"),
        }
    }
}

impl Default for TransactionStreamStatus {
    fn default() -> TransactionStreamStatus {
        Self::UNKNOWN
    }
}




